### PR TITLE
(#133) Upgrade to support Visual Studio 2022

### LINKED ISSUE #133: migrate to VS-2022
*Cake for Visual Studio* does not show up on the list of extensions for VS 2022.

Additionally to modifying the version in the manifest it seems there is more to do for a migration.

* [Announcement of VS 2022 preview 1](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-preview-1-now-available/)
* [Update a Visual Studio extension for Visual Studio 2022](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022)

### PR DESCRIPTION
**Pull request by gep13**
The work done in this commit is as a result of following along with
this article:

https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

There is still work to be done here but this is a good start.

Fixes #133

### CODE REVIEW

**Comment by gep13** [comment]
@nils-a here is the work to date on upgrading to support Visual Studio 2022.  Still very rough around the edges, but this is the work that we have been doing on stream the last couple of weeks.

**Comment by nils-a** [comment]
@gep13 Snippets are currently broken in develop, see #134.
Should we fix that first or do the fix "directly" is this PR? (I see no real benefit of having a separate PR for #134 except that it would be much cleaner than doing all-in-one here.)

**Comment by gep13** [comment]
@nils-a I would be happy to do that work in this PR, and get everything working here, ready to test in both 2019 and 2022.

**Comment by nils-a** [comment]
@gep13 I think this is it. Everything I can think of is now working again.

**Pull request merged**
