### PR TITLE
(GH-18) Improvements to CI build scripts

### PR DESCRIPTION
**Pull request by agc93**
Was just wondering why I hadn't got any feedback on the PR we discussed @gep13 , but turns out I never raised it :confounded: 

This is all pretty experimental stuff so let me know what you think before we either a) merge to `develop` and start the trial and error or b) temporarily change the `ShouldPublishToMyGet` condition to start building PRs as well (to build and package this one) and trial and error it that way.

Thoughts/comments etc?

### CODE REVIEW

**Comment by gep13** [comment]
Building PR's won't work, as the required secure environment variables won't be hydrated during the build.

I would suggest just going for it 😄

**Comment by agc93** [comment]
So everything looks at least vaguely correct to you @gep13 ?

**Comment by gep13** [comment]
@agc93 enough that I would be happy to take it for a spin, yes 👍

**Comment by agc93** [comment]
Let the trial and error experiments begin 😅

**Pull request merged**
