### PR TITLE
To Master

### PR DESCRIPTION
**Pull request by tdashworth**
Hi all,

The last commit to master was the end of 2017 and there have been contributed feature (such as VS 2019 support). 

What is the timeline to actually push contributions out to new releases?

Thanks

### CODE REVIEW

**Comment by gep13** [comment]
@tdashworth the next release is based on the following milestone:

https://github.com/cake-build/cake-vs/milestone/5

Once that is completed, a new release will ship.

**Comment by tdashworth** [comment]
@gep13 Thank you! Looks like its been actively worked on. Any timeframe for this?

**Comment by gep13** [comment]
@tdashworth no, not that I am aware of.  This is an open source project, contributed to by people in their spare time, so as a result, there is no concept of timeframes for anything.

**Comment by tdashworth** [comment]
@gep13 That's understandable. Thank you for your quick responses :)

**Pull request closed without merging**
