### PR TITLE
(GH-29) Add support for -experimental flag

### LINKED ISSUE #29: The extension doesn't support the -experimental flag
I use the `-experimental` flag to enable C# 6 features. Apparently the extension doesn't provide a way to pass this flag to cake.exe, so my Cake tasks fail to compile.

### PR DESCRIPTION
**Pull request by agc93**
Resolves #29

### CODE REVIEW

**Comment by gep13** [comment]
Hmm, is this going to work?  Can I set both `debug` and `experimental`, or is it one or the other?

You would need both if you wanted to debug an experimental cake script.

**Comment by devlead** [comment]
@gep13 debug and experimental are separate things. One is flag for if debugging and one specifies which version of Roslyn to use. They can be combined.

**Comment by gep13** [comment]
@devlead right. So with this implementation, haven't tested it, I think we get another button in the task runner that allow the running of a task in either debug, or experimental. I think we need to have it be possible to run debug and experimental.

**Comment by agc93** [comment]
I haven't tested both, but you *should* be able to specify multiple by clicking on both the debug and experimental options. Does that not work?

**Comment by agc93** [comment]
I just tested this branch, and was able to specify multiple by clicking on both the debug and experimental options and it just adds both options on the CLI. Does that sound right?
screenshot 82

**Comment by gep13** [comment]
Yes, perfect!

**Pull request merged**
