### PR TITLE
Added Solution Item Template

### PR DESCRIPTION
**Pull request by dlbroadfoot**
The existing item template only works when you go to add a new item to a C# project.

This PR adds support so you can right click on the Solution and add a new Cake script. It will then appear in the Solution Items folder in Visual Studio.

### CODE REVIEW

**Comment by dlbroadfoot** [comment]
Not sure if this repo is still active. Is it possible to get a review please @gep13  @agc93

**Comment by gep13** [comment]
@dlbroadfoot it is.  Reviewing this PR is on my list of things to do, but there are quite a few things ahead of it in the list 😢

**Comment by dlbroadfoot** [comment]
No worries @gep13 - thanks for taking the time to review when you do get a chance.

**Comment by agc93** [comment]
Thanks for your contribution @dlbroadfoot !

I've cherry-picked out your change and committed it (as 39bbe83bf828051f417a7779507cb4c2c20d70de) as I'd like to clean the build up properly. This should appear in a [prerelease version](https://cakebuild.net/blog/2016/12/cake-vs-prerelease) shortly.

Thanks again for the awesome work!

**Pull request closed without merging**
